### ISSUE TITLE
Annotations problem

### ISSUE THREAD

**Issue by AhmedElsherbini** [dmnfarrell/pathogenie#4]
Hi Damien,

It is my first time using your script for annotating my bacterial FASTA sequence. From the console of my python (3.8) on Ubuntu/Linux 20.10, I see the script stuck with Aragon. I updated all dependencies; however, I still get the same error.
""
Traceback (most recent call last):

  File "<ipython-input-5-d8d33a6c4242>", line 11, in <module>
    featdf,recs = pathogenie.app.run_annotation(infile, threads=10, kingdom='bacteria')

  File "/home/ahmed/src/pathogenie/pathogenie/app.py", line 461, in run_annotation
    arag = aragorn(infile)

  File "/home/ahmed/src/pathogenie/pathogenie/app.py", line 333, in aragorn
    df = tools.read_aragorn(outfile)

  File "/home/ahmed/src/pathogenie/pathogenie/tools.py", line 841, in read_aragorn
    if m.group(1):

AttributeError: 'NoneType' object has no attribute 'group' 
"""
#######################################################
This error refers to this chunk specifically in tools.py script

 m = re.match('(c*)\[(\d+),(\d+)\]', cols[2])
                if m:
                    start = int(m.group(2)) - 1
                    end = int(m.group(3))
                if m.group(1): #here I change
                    rstrand = -1
                else:
                    rstrand = 1
                res.append([contig, name, feat_type, start, end, anticodon, rstrand])
#######################################################
Any advice for fixing this issue?
Ps: I tried using the GUI and no output for annotation work.
Thanks in advance.

**Comment by dmnfarrell** [comment]
Are you sure the output from aragorn is not empty? I'd have to see all the output. Make sure your input file exists.

**Comment by AhmedElsherbini** [comment]
Dear Damien,
Absolutely, input file exists (as contigs.fasta ) ! And the output is only 4 files named (hmm. out, unknowns.fasta, tempseq_blast.txt , tempseq.fa).

the console is showing this!
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...5497081 bp seq created, 57.11 pct GC
Locating all potential starts and stops...278776 nodes
Looking for GC bias in different frames...frame bias scores: 0.60 0.14 2.26
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (8624 bp)...done!
Finding genes in sequence #2 (15994 bp)...done!
Finding genes in sequence #3 (4096 bp)...done!
Finding genes in sequence #4 (94245 bp)...done!
Finding genes in sequence #5 (172895 bp)...done!
Finding genes in sequence #6 (249203 bp)...done!
Finding genes in sequence #7 (9377 bp)...done!
Finding genes in sequence #8 (152 bp)...done!
Finding genes in sequence #9 (2287 bp)...done!
Finding genes in sequence #10 (4964 bp)...done!
Finding genes in sequence #11 (63637 bp)...done!
Finding genes in sequence #12 (158 bp)...done!
Finding genes in sequence #13 (1712 bp)...done!
Finding genes in sequence #14 (370946 bp)...done!
Finding genes in sequence #15 (79 bp)...done!
Finding genes in sequence #16 (215 bp)...done!
Finding genes in sequence #17 (122 bp)...done!
Finding genes in sequence #18 (1185 bp)...done!
Finding genes in sequence #19 (3664 bp)...done!
Finding genes in sequence #20 (20245 bp)...done!
Finding genes in sequence #21 (164515 bp)...done!
Finding genes in sequence #22 (187 bp)...done!
Finding genes in sequence #23 (333 bp)...done!
Finding genes in sequence #24 (239 bp)...done!
Finding genes in sequence #25 (78 bp)...done!
Finding genes in sequence #26 (243 bp)...done!
Finding genes in sequence #27 (420 bp)...done!
Finding genes in sequence #28 (312 bp)...done!
Finding genes in sequence #29 (881 bp)...done!
Finding genes in sequence #30 (99 bp)...done!
Finding genes in sequence #31 (198 bp)...done!
Finding genes in sequence #32 (41726 bp)...done!
Finding genes in sequence #33 (251 bp)...done!
Finding genes in sequence #34 (479 bp)...done!
Finding genes in sequence #35 (150 bp)...done!
Finding genes in sequence #36 (4482 bp)...done!
Finding genes in sequence #37 (892 bp)...done!
Finding genes in sequence #38 (36577 bp)...done!
Finding genes in sequence #39 (258 bp)...done!
Finding genes in sequence #40 (6882 bp)...done!
Finding genes in sequence #41 (86804 bp)...done!
Finding genes in sequence #42 (159221 bp)...done!
Finding genes in sequence #43 (2339 bp)...done!
Finding genes in sequence #44 (34393 bp)...done!
Finding genes in sequence #45 (1231 bp)...done!
Finding genes in sequence #46 (152 bp)...done!
Finding genes in sequence #47 (9006 bp)...done!
Finding genes in sequence #48 (152 bp)...done!
Finding genes in sequence #49 (2625 bp)...done!
Finding genes in sequence #50 (100 bp)...done!
Finding genes in sequence #51 (152456 bp)...done!
Finding genes in sequence #52 (101 bp)...done!
Finding genes in sequence #53 (133 bp)...done!
Finding genes in sequence #54 (1324 bp)...done!
Finding genes in sequence #55 (2815 bp)...done!
Finding genes in sequence #56 (303 bp)...done!
Finding genes in sequence #57 (282 bp)...done!
Finding genes in sequence #58 (3080 bp)...done!
Finding genes in sequence #59 (847 bp)...done!
Finding genes in sequence #60 (10084 bp)...done!
Finding genes in sequence #61 (84797 bp)...done!
Finding genes in sequence #62 (1918 bp)...done!
Finding genes in sequence #63 (106 bp)...done!
Finding genes in sequence #64 (2202 bp)...done!
Finding genes in sequence #65 (375146 bp)...done!
Finding genes in sequence #66 (15787 bp)...done!
Finding genes in sequence #67 (330 bp)...done!
Finding genes in sequence #68 (195278 bp)...done!
Finding genes in sequence #69 (507 bp)...done!
Finding genes in sequence #70 (217 bp)...done!
Finding genes in sequence #71 (253 bp)...done!
Finding genes in sequence #72 (111 bp)...done!
Finding genes in sequence #73 (84 bp)...done!
Finding genes in sequence #74 (5476 bp)...done!
Finding genes in sequence #75 (155 bp)...done!
Finding genes in sequence #76 (85 bp)...done!
Finding genes in sequence #77 (155 bp)...done!
Finding genes in sequence #78 (526 bp)...done!
Finding genes in sequence #79 (1037 bp)...done!
Finding genes in sequence #80 (98 bp)...done!
Finding genes in sequence #81 (134011 bp)...done!
Finding genes in sequence #82 (429660 bp)...done!
Finding genes in sequence #83 (20446 bp)...done!
Finding genes in sequence #84 (254 bp)...done!
Finding genes in sequence #85 (159569 bp)...done!
Finding genes in sequence #86 (3960 bp)...done!
Finding genes in sequence #87 (152 bp)...done!
Finding genes in sequence #88 (78 bp)...done!
Finding genes in sequence #89 (12469 bp)...done!
Finding genes in sequence #90 (3064 bp)...done!
Finding genes in sequence #91 (1611 bp)...done!
Finding genes in sequence #92 (229 bp)...done!
Finding genes in sequence #93 (361 bp)...done!
Finding genes in sequence #94 (768 bp)...done!
Finding genes in sequence #95 (255 bp)...done!
Finding genes in sequence #96 (175 bp)...done!
Finding genes in sequence #97 (1196 bp)...done!
Finding genes in sequence #98 (280 bp)...done!
Finding genes in sequence #99 (152 bp)...done!
Finding genes in sequence #100 (434 bp)...done!
Finding genes in sequence #101 (135477 bp)...done!
Finding genes in sequence #102 (86 bp)...done!
Finding genes in sequence #103 (194 bp)...done!
Finding genes in sequence #104 (162 bp)...done!
Finding genes in sequence #105 (215 bp)...done!
Finding genes in sequence #106 (83334 bp)...done!
Finding genes in sequence #107 (214 bp)...done!
Finding genes in sequence #108 (377210 bp)...done!
Finding genes in sequence #109 (238 bp)...done!
Finding genes in sequence #110 (330 bp)...done!
Finding genes in sequence #111 (80 bp)...done!
Finding genes in sequence #112 (433 bp)...done!
Finding genes in sequence #113 (113 bp)...done!
Finding genes in sequence #114 (232 bp)...done!
Finding genes in sequence #115 (907 bp)...done!
Finding genes in sequence #116 (1484 bp)...done!
Finding genes in sequence #117 (2643 bp)...done!
Finding genes in sequence #118 (113 bp)...done!
Finding genes in sequence #119 (2091 bp)...done!
Finding genes in sequence #120 (640436 bp)...done!
Finding genes in sequence #121 (81 bp)...done!
Finding genes in sequence #122 (4074 bp)...done!
Finding genes in sequence #123 (200 bp)...done!
Finding genes in sequence #124 (329 bp)...done!
Finding genes in sequence #125 (15621 bp)...done!
Finding genes in sequence #126 (159 bp)...done!
Finding genes in sequence #127 (661 bp)...done!
Finding genes in sequence #128 (13372 bp)...done!
Finding genes in sequence #129 (24145 bp)...done!
Finding genes in sequence #130 (876 bp)...done!
Finding genes in sequence #131 (78 bp)...done!
Finding genes in sequence #132 (1356 bp)...done!
Finding genes in sequence #133 (759 bp)...done!
Finding genes in sequence #134 (207 bp)...done!
Finding genes in sequence #135 (91 bp)...done!
Finding genes in sequence #136 (11355 bp)...done!
Finding genes in sequence #137 (1367 bp)...done!
Finding genes in sequence #138 (306 bp)...done!
Finding genes in sequence #139 (292 bp)...done!
Finding genes in sequence #140 (80 bp)...done!
Finding genes in sequence #141 (9302 bp)...done!
Finding genes in sequence #142 (148 bp)...done!
Finding genes in sequence #143 (138 bp)...done!
Finding genes in sequence #144 (569 bp)...done!
Finding genes in sequence #145 (879 bp)...done!
Finding genes in sequence #146 (26222 bp)...done!
Finding genes in sequence #147 (199149 bp)...done!
Finding genes in sequence #148 (5080 bp)...done!
Finding genes in sequence #149 (182 bp)...done!
Finding genes in sequence #150 (85 bp)...done!
Finding genes in sequence #151 (1870 bp)...done!
Finding genes in sequence #152 (1187 bp)...done!
Finding genes in sequence #153 (96 bp)...done!
Finding genes in sequence #154 (80 bp)...done!
Finding genes in sequence #155 (100685 bp)...done!
Finding genes in sequence #156 (1688 bp)...done!
Finding genes in sequence #157 (153381 bp)...done!
Finding genes in sequence #158 (309 bp)...done!
Finding genes in sequence #159 (1159 bp)...done!
Finding genes in sequence #160 (3978 bp)...done!
Finding genes in sequence #161 (362183 bp)...done!
Finding genes in sequence #162 (288 bp)...done!
Finding genes in sequence #163 (193 bp)...done!
Finding genes in sequence #164 (139 bp)...done!
Finding genes in sequence #165 (152 bp)...done!
Finding genes in sequence #166 (2708 bp)...done!
Finding genes in sequence #167 (1714 bp)...done!
Finding genes in sequence #168 (240 bp)...done!
Finding genes in sequence #169 (59037 bp)...done!
Finding genes in sequence #170 (1594 bp)...done!
Finding genes in sequence #171 (116 bp)...done!
Finding genes in sequence #172 (94 bp)...done!
Finding genes in sequence #173 (179 bp)...done!
Finding genes in sequence #174 (4144 bp)...done!
Finding genes in sequence #175 (122 bp)...done!
Finding genes in sequence #176 (30636 bp)...done!
/home/ahmed/.config/pathogenie/prokka/IS.fa
blasting 5082 ORFs to IS
blastp -out tempseq_blast.txt -outfmt "6 qseqid sseqid qseq sseq pident qcovs length mismatch gapopen qstart qend sstart send evalue bitscore stitle" -query tempseq.fa -db /home/ahmed/.config/pathogenie/prokka/IS.fa -evalue 1e-10 -max_target_seqs 1 -num_threads 8
5027 sequences unassigned
/home/ahmed/.config/pathogenie/prokka/amr.fa
blasting 5027 ORFs to amr
blastp -out tempseq_blast.txt -outfmt "6 qseqid sseqid qseq sseq pident qcovs length mismatch gapopen qstart qend sstart send evalue bitscore stitle" -query tempseq.fa -db /home/ahmed/.config/pathogenie/prokka/amr.fa -evalue 1e-100 -max_target_seqs 1 -num_threads 8
5010 sequences unassigned
/home/ahmed/.config/pathogenie/prokka/sprot_bacteria.fa
blasting 5010 ORFs to sprot_bacteria
blastp -out tempseq_blast.txt -outfmt "6 qseqid sseqid qseq sseq pident qcovs length mismatch gapopen qstart qend sstart send evalue bitscore stitle" -query tempseq.fa -db /home/ahmed/.config/pathogenie/prokka/sprot_bacteria.fa -evalue 0.0001 -max_target_seqs 1 -num_threads 8
2599 sequences unassigned
running hmmer
/home/ahmed/.config/pathogenie/hmms/HAMAP.hmm
hmmscan --noali --notextw --acc -E 1e-4 --cpu 8 --tblout /home/ahmed/.config/pathogenie/tmp/hmm.txt -o hmm.out /home/ahmed/.config/pathogenie/hmms/HAMAP.hmm unknowns.fa
running aragorn
Traceback (most recent call last):

  File "<ipython-input-4-021f63a5fa91>", line 5, in <module>
    featdf,recs = pathogenie.app.run_annotation(infile, threads=8, kingdom='bacteria')

  File "/home/ahmed/src/pathogenie/pathogenie/app.py", line 461, in run_annotation
    arag = aragorn(infile)

  File "/home/ahmed/src/pathogenie/pathogenie/app.py", line 333, in aragorn
    df = tools.read_aragorn(outfile)

  File "/home/ahmed/src/pathogenie/pathogenie/tools.py", line 841, in read_aragorn
    if m.group(1):

AttributeError: 'NoneType' object has no attribute 'group'
